services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - my-network
    depends_on:
      - database

  database:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - /my/own/datadir:/var/lib/postgresql/data
    networks:
      - my-network

  httpd:
    container_name: httpd
    build:
      context: ./httpServer
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network:
    driver: bridge
