name: CI Build and Push Docker Image

on:
  workflow_run:
    workflows: ["CI Test Backend"]
    branches: [main]
    types: [completed]

jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        run: echo "Hello from develop 2"
        # uses: actions/checkout@v2.5.0

      # - name: Login to DockerHub
      #   run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push backend image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./backend
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:latest
      #     push: true

      # - name: Build and push database image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./postgres
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-postgres:latest
      #     push: true

      # - name: Build and push HTTP server image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./httpServer
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
      #     push: true
